version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    depends_on:
      - memory_game
    networks:
      - game-network

  memory_game:
    build:
      context: .
      dockerfile: Dockerfile.memory
    ports:
      - "5001:5001"
    networks:
      - game-network

networks:
  game-network: